### ISSUE TITLE
无法连接mirai overflow，请求支持 get_version_info API

### ISSUE THREAD

**Issue by XuanSuHS** [linyuchen/LiteLoaderQQNT-OneBotApi#44]
QQ版本：`Windows 9.9.7-21484 x64`

LLOneBot版本：`v3.1.2`

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：mirai-overflow

BUG描述：插件开启正向ws服务器，尝试用mirai overflow连接失败。阅读log发现overflow在向插件发送未支持的get_version_info

下面附上overflow日志：
```
2024-02-16 17:47:37 I/Onebot: Overflow v2.16.0-c7971b9-SNAPSHOT 正在运行
2024-02-16 17:47:37 I/Onebot: 连接到 WebSocket: ws://127.0.0.1:14514
2024-02-16 17:47:37 I/Onebot: ▌ 已连接到服务器 ┈━═☆
2024-02-16 17:47:37 W/stderr: Exception in thread "DefaultDispatcher-worker-1" java.lang.NullPointerException
2024-02-16 17:47:37 W/stderr:   at cn.evolvefield.onebot.client.util.ListenerUtils.getMessageType(ListenerUtils.kt:51)
2024-02-16 17:47:37 W/stderr:   at cn.evolvefield.onebot.client.util.ListenerUtils.getMessageType(ListenerUtils.kt:15)
2024-02-16 17:47:37 W/stderr:   at cn.evolvefield.onebot.client.handler.EventBus.onReceive(EventBus.kt:39)
2024-02-16 17:47:37 W/stderr:   at cn.evolvefield.onebot.client.connection.WSClient$onMessage$1.invokeSuspend(WSClient.kt:65)
2024-02-16 17:47:37 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-02-16 17:47:37 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2024-02-16 17:47:37 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2024-02-16 17:47:37 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2024-02-16 17:47:37 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2024-02-16 17:47:37 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2024-02-16 17:47:37 W/stderr:   Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(overflow), StandaloneCoroutine{Cancelling}@12a195b3, Dispatchers.Default]
2024-02-16 17:47:47 W/Onebot: Request failed: [get_version_info, echo=0] Timed out waiting for 10000 ms
2024-02-16 17:47:47 I/Onebot: 服务端版本信息
{
  "status": "failed",
  "retcode": -1,
  "message": "Timed out waiting for 10000 ms"
}
2024-02-16 17:47:47 W/stderr: Exception in thread "DefaultDispatcher-worker-1" java.lang.NullPointerException
2024-02-16 17:47:47 W/stderr:   at cn.evolvefield.onebot.client.util.ListenerUtils.getMessageType(ListenerUtils.kt:51)
2024-02-16 17:47:47 W/stderr:   at cn.evolvefield.onebot.client.util.ListenerUtils.getMessageType(ListenerUtils.kt:15)
2024-02-16 17:47:47 W/stderr:   at cn.evolvefield.onebot.client.handler.EventBus.onReceive(EventBus.kt:39)
2024-02-16 17:47:47 W/stderr:   at cn.evolvefield.onebot.client.connection.WSClient$onMessage$1.invokeSuspend(WSClient.kt:65)
2024-02-16 17:47:47 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-02-16 17:47:47 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2024-02-16 17:47:47 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2024-02-16 17:47:47 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2024-02-16 17:47:47 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2024-02-16 17:47:47 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2024-02-16 17:47:47 W/stderr:   Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(overflow), StandaloneCoroutine{Cancelling}@41ea15aa, Dispatchers.Default]
2024-02-16 17:47:57 W/Onebot: Request failed: [get_login_info, echo=1] Timed out waiting for 10000 ms
2024-02-16 17:47:57 E/main: Failed to init MiraiConsole.
java.lang.NullPointerException: Cannot read field "userId" because "it.data" is null
        at cn.evolvefield.onebot.client.core.Bot.getLoginInfo(Bot.kt:586)
        at cn.evolvefield.onebot.client.core.Bot$getLoginInfo$1.invokeSuspend(Bot.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at top.mrxiaom.overflow.internal.plugin.OverflowCoreAsPlugin$TheLoader.enable(OverflowCoreAsPlugin.kt:156)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:193)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:360)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:512)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:182)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:181)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:59)`
```

复现步骤： 使用 [overflow](https://mirai.mrxiaom.top/#get-started) / [(github)](https://github.com/MrXiaoM/Overflow) 连接插件

LLOneBot日志:
```
2024/2/16 17:47:37 BOT(x): event上报ws客户端已连接 
2024/2/16 17:47:37 BOT(x): 收到ws消息 {"action":"get_version_info","echo":0} 
2024/2/16 17:47:47 BOT(x): 收到ws消息 {"action":"get_login_info","echo":1} 
2024/2/16 17:47:59 BOT(x): event上报ws客户端已断开 
```

另外，有机会支持一下鉴权吗，感觉这样会安全一些（

**Comment by linyuchen** [comment]
后续版本会加上

**Comment by linyuchen** [comment]
[v3.2.0](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)已添加

**Comment by XuanSuHS** [comment]
感谢！

**Comment by XuanSuHS** [comment]
但是又发现了一个问题，插件在收到任意带参数的请求的时候会直接卡住，比如`ws://127.0.0.1:14514?access_token=moe`
而overflow就是这么传递参数的，导致带token时overflow就无法连接到插件了
感觉可以新开一个issue（
